# Generated by Django 4.2.7 on 2023-11-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=80)),
                ('years', models.IntegerField()),
                ('motors', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_number', models.CharField(max_length=10)),
                ('car_number', models.CharField(max_length=8)),
                ('car_yoqilgi', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=80)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
